name = input("Enter your full name")
phone_number = input("Enter your phone number")

result = len(name)
result = name.find(" ")
result = name.rfind("4")
name = name.capitalize()
name = name.upper()
name = name.lower()
result = name.isdigit()
result = name.isalpha()
result = phone_number.count("-")
phone_number = phone_number.replace("-", (" "))
print(name)
print(result)
print(phone_number)